FROM alpine:3.15

ENV PROJECT_PATH=/chirpstack-docs

RUN apk add --no-cache python3 python3-dev py3-pip make gcc musl-dev graphviz ttf-freefont bash git

RUN mkdir -p $PROJECT_PATH
COPY . $PROJECT_PATH
WORKDIR $PROJECT_PATH

RUN pip install -r requirements.txt
RUN pip install jinja2==3.0.0
